[tool.commitizen]
version = "0.0.1"
version_files = [
    "pyproject.toml",
    "src/__version__.py",
]
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "bump: $current_version → $new_version [skip-ci]"
